// Content for the PFW-SIF research report pages (site/reports/*.html).
// Initiation reports use only information public on their publication date.
// Prices are Tiingo closes; charts come from tools/report-data/weekly-prices.json.
// Rebuild with: node tools/build-reports.mjs

export const reports = [
  {
    slug: "aapl-2015-initiation",
    ticker: "AAPL", exchange: "NASDAQ", company: "Apple Inc.",
    sector: "Information Technology", industry: "Technology Hardware",
    type: "Initiation", date: "2015-12-21", rating: "BUY",
    team: "Information Technology team",
    decision: "Approved", decisionDate: "2015-12-22",
    executed: { date: "2016-01-04", price: 105.35 },
    price: 107.33, target: 135,
    kpis: [["Trailing P/E", "11.6x", "FY2015 EPS $9.22"], ["Dividend yield", "1.9%", "$0.52 quarterly"]],
    headline: "Priced for peak iPhone, built for a decade of Services",
    thesis: [
      "We recommend initiating a position in Apple. At about $107 the stock trades near 11.6 times trailing earnings, below the S&P 500 multiple and lower still after its net cash. The market is pricing Apple as a hardware maker whose best product has peaked.",
      "We think that view misses three things. The installed base keeps growing, and customers rarely leave the ecosystem. Services revenue grows with that base rather than with new unit sales. And the cash flow is large enough to fund a $200 billion capital return program while still adding to the balance sheet.",
      "Fiscal 2015 was a record year: revenue up 28% to $233.7 billion, 231 million iPhones sold, and Greater China revenue up 84%. Even if fiscal 2016 iPhone units decline, the stock already discounts that outcome.",
    ],
    catalysts: [
      ["Services visibility", "Services reached about $20 billion in fiscal 2015. As it grows faster than hardware and is disclosed in more detail, we expect investors to value it like a software business."],
      ["Capital return update", "Apple usually expands its buyback and dividend each spring. A larger program would shrink the share count further."],
      ["Upgrade cycle", "Hundreds of millions of users are still on iPhones older than the iPhone 6. The fall 2016 iPhone gives them a reason to upgrade."],
      ["China and emerging markets", "Rising incomes in China and India expand the market for premium smartphones."],
    ],
    risks: [
      ["iPhone 6s cycle", "Reports of supplier order cuts suggest fiscal 2016 iPhone units could decline from the record year."],
      ["China slowdown", "A weaker Chinese economy and currency could hit Apple's fastest-growing region."],
      ["Product concentration", "iPhone is about two-thirds of revenue."],
      ["Unproven new categories", "Apple Watch has not shown it can become a major product line."],
    ],
    financials: {
      note: "Fiscal years end in late September. $ billions except per share. Split-adjusted EPS as reported at the time.",
      cols: ["FY2013", "FY2014", "FY2015"],
      rows: [
        ["Revenue", "170.9", "182.8", "233.7"],
        ["Revenue growth", "9.2%", "7.0%", "27.9%"],
        ["Gross margin", "37.6%", "38.6%", "40.1%"],
        ["Net income", "37.0", "39.5", "53.4"],
        ["Diluted EPS ($)", "5.68", "6.45", "9.22"],
        ["Operating cash flow", "53.7", "59.7", "81.3"],
      ],
    },
    valuation: {
      method: "Normalized earnings plus net cash",
      rows: [["Normalized EPS", "$9.00"], ["Target multiple", "13x"], ["Value of operations", "$117"], ["Net cash per share", "~$24"], ["Less tax on repatriating overseas cash", "−$6"], ["12-month target", "$135"]],
      text: "We apply a modest 13x multiple, close to the market, to normalized earnings of about $9 a share and add net cash. Most of Apple's cash sits overseas, so we haircut it for the US tax that would be due if it were brought home.",
    },
    caseTitle: "Why we are buying Apple",
    caseSections: [
      ["The market's mistake", "Investors treat each iPhone cycle as a one-time event and value Apple on the assumption that the next one will be smaller. In reality, each cycle starts from a larger installed base of loyal customers. Apple's revenue is better described as a subscription to the ecosystem, paid every two or three years, than as a series of hit products."],
      ["The ecosystem is the asset", "iOS, iCloud, iMessage and the App Store tie a user's photos, apps and contacts to Apple devices. Switching to Android means losing purchases and habits. That stickiness lets Apple charge premium prices and earn about 40% gross margins in a hardware business where competitors earn far less."],
      ["Services: a second business hiding in plain sight", "Services, at about $20 billion, would rank among the 150 largest US companies on its own. It grows with the number of active devices, not with new unit sales, and carries higher margins than hardware. At today's price investors pay almost nothing for it."],
      ["Shareholder returns", "Apple pays $0.52 a quarter and is midway through a $200 billion capital return program. At this valuation, buybacks retire shares at roughly an 8–9% earnings yield, which mechanically raises earnings per share each year."],
      ["What would make us wrong", "A shrinking installed base for two consecutive years, a cut to the capital return program, or Services growth falling below growth in active devices. Any of these would mean the ecosystem is weakening, and we would sell."],
    ],
    icRationale: "The committee approved a full position at one quarter of the fund's starting capital. Members agreed that near-term iPhone weakness was already priced in and that the risk/reward favored buying before the spring capital return update.",
    vote: "Approved 6–1",
    file: "2015-12-21-aapl-initiation.md",
  },
  {
    slug: "googl-2016-initiation",
    ticker: "GOOGL", exchange: "NASDAQ", company: "Alphabet Inc.",
    sector: "Communication Services", industry: "Interactive Media & Services",
    type: "Initiation", date: "2016-01-05", rating: "BUY",
    team: "Communication Services team",
    decision: "Approved", decisionDate: "2016-01-07",
    executed: { date: "2016-01-11", price: 733.07 },
    price: 761.53, target: 900,
    kpis: [["Q3 2015 revenue growth", "13%", "21% constant currency"], ["Cash & securities", "$73B", "No meaningful debt"]],
    headline: "Mobile search, YouTube and a new era of cost discipline",
    thesis: [
      "We recommend initiating a position in Alphabet Class A shares. Search is moving to mobile without losing its economics. Paid clicks grew about 23% last quarter, and YouTube is taking brand advertising from television.",
      "The October 2015 reorganization into Alphabet separates the core Google business from long-shot projects such as self-driving cars and life sciences. New CFO Ruth Porat has brought cost discipline, and the company announced its first share buyback, about $5.1 billion.",
      "Starting with Q4 2015 results, Alphabet will report Google and Other Bets separately. We expect that to show how profitable the core business is once billions of Other Bets losses are stripped out.",
    ],
    catalysts: [
      ["Segment reporting", "Q4 2015 results, due in early February, will be the first to show Google and Other Bets separately."],
      ["Mobile monetization", "Mobile search ads and new formats on YouTube should close the price gap between mobile and desktop ads."],
      ["Cost discipline", "Slower headcount growth and capital spending targets under the new CFO should lift margins."],
      ["Buybacks", "The first repurchase program signals a willingness to return cash. Future programs could be larger."],
    ],
    risks: [
      ["Regulation", "The European Commission's Google Shopping antitrust case is ongoing, and fines or remedies are possible."],
      ["Other Bets spending", "These projects lose billions a year, and the timing of any payoff is uncertain."],
      ["Falling ad prices", "Cost-per-click keeps declining as traffic shifts to mobile and emerging markets."],
      ["Strong dollar", "About half of revenue comes from outside the US, so currency moves reduce reported growth."],
    ],
    financials: {
      note: "$ billions. Q3 2015 is the most recent quarter reported at publication.",
      cols: ["2013", "2014", "Q3 2015"],
      rows: [
        ["Revenue", "55.5", "66.0", "18.7"],
        ["Revenue growth", "19%", "19%", "13%"],
        ["Net income", "12.9", "14.4", "4.0"],
        ["Paid click growth", "—", "—", "~23%"],
        ["Cash & securities", "58.7", "64.4", "72.8"],
      ],
    },
    valuation: {
      method: "Forward earnings multiple plus net cash",
      rows: [["2016E EPS (non-GAAP)", "~$33"], ["Target multiple", "24x"], ["Value of operations", "~$790"], ["Net cash per share", "~$105"], ["12-month target", "$900"]],
      text: "At the pitch price Alphabet traded at about 23x forward earnings, or under 20x excluding cash. That is a modest premium to the market for a business growing in the mid-teens with very high returns on capital. A 24x multiple plus net cash gives about $900.",
    },
    caseTitle: "Why we are buying Alphabet",
    caseSections: [
      ["Search is the best business on the internet", "Search ads reach people at the moment they want something, so advertisers pay for intent rather than impressions. Google handles the large majority of searches in most markets, and Android and Chrome keep its distribution secure as usage moves to phones."],
      ["Mobile is additive, not a threat", "The bear case says mobile ads earn less than desktop ads. But mobile is increasing the number of searches, and paid clicks are growing faster than at any point in the past few years. Lower prices per click are offset by much higher volume."],
      ["YouTube is the next television", "YouTube is the leading destination for online video. As brand budgets move from TV to online video, YouTube is positioned to capture a large share, with years of growth ahead."],
      ["Alphabet adds discipline", "The holding-company structure makes management accountable for the core business's margins and for the cash spent on Other Bets. The first buyback and a new CFO from Wall Street show that the company now thinks about shareholder returns."],
      ["What would make us wrong", "Sustained declines in paid-click growth, regulation that restricts how Google ranks its own services, or Other Bets losses that keep growing without any milestones."],
    ],
    icRationale: "The committee approved Alphabet over the Intel pitch at the same meeting, citing its higher growth, net cash and the expected margin uplift from Alphabet's new reporting.",
    vote: "Approved 5–2",
    file: "2016-01-05-googl-initiation.md",
  },
  {
    slug: "intc-2016-pitch",
    ticker: "INTC", exchange: "NASDAQ", company: "Intel Corporation",
    sector: "Information Technology", industry: "Semiconductors",
    type: "Initiation", date: "2016-01-06", rating: "BUY",
    team: "Information Technology team",
    decision: "Not approved", decisionDate: "2016-01-07",
    price: 33.08, target: 40,
    kpis: [["Trailing P/E", "~13x", "Below the market"], ["Dividend yield", "2.9%", "$0.24 quarterly"]],
    headline: "Data center and Altera to offset a shrinking PC market",
    thesis: [
      "The team recommended Intel as a cash-rich leader whose data center business was growing while the market focused on falling PC sales.",
      "The Data Center Group earned $4.1 billion of revenue in Q3 2015, up 12%. Intel holds over 95% of the server CPU market. The $16.7 billion Altera acquisition, closed in December 2015, adds programmable chips used in networking and cloud data centers.",
      "At about 13x earnings with a nearly 3% yield, the team argued the shares priced in permanent PC decline and nothing for data center growth.",
    ],
    catalysts: [
      ["Cloud build-out", "Hyperscale cloud providers are buying servers at a record pace, nearly all of them Intel-based."],
      ["Altera integration", "Combining FPGAs with Xeon processors opens new data center products."],
      ["Memory and IoT", "New memory technology and Internet of Things chips add growth options."],
      ["Capital return", "Dividend increases and buybacks are supported by about $20 billion of operating cash flow a year."],
    ],
    risks: [
      ["PC decline", "Over half of revenue still comes from PCs, a market that fell about 10% in 2015."],
      ["Mobile failure", "Intel spent billions subsidizing tablet chips and still has no position in smartphones."],
      ["Manufacturing schedule", "The 10nm process is late, which could narrow Intel's manufacturing lead."],
      ["Competition", "ARM-based server chips and a resurgent AMD could pressure data center share."],
    ],
    financials: {
      note: "$ billions. Q3 2015 is the most recent quarter reported at publication.",
      cols: ["2013", "2014", "Q3 2015"],
      rows: [
        ["Revenue", "52.7", "55.9", "14.5"],
        ["Net income", "9.6", "11.7", "3.1"],
        ["Data Center Group revenue", "11.2", "14.4", "4.1"],
        ["DCG growth", "8%", "18%", "12%"],
      ],
    },
    valuation: {
      method: "Earnings multiple",
      rows: [["2016E EPS", "~$2.50"], ["Target multiple", "16x"], ["12-month target", "$40"]],
      text: "The team applied a market multiple to 2016 earnings, arguing that data center growth deserved at least parity with the S&P 500.",
    },
    caseTitle: "Why the committee passed on Intel",
    caseSections: [
      ["The bull case presented", "A dominant server CPU franchise, a 3% dividend yield and a low multiple. The team saw Intel as a value stock with a hidden growth business."],
      ["Too much PC exposure", "Members thought data center growth would struggle to offset a PC business that was more than half of revenue and shrinking."],
      ["Manufacturing risk", "Delays at 10nm raised the question of whether Intel's manufacturing lead, its key competitive advantage, would hold."],
      ["Opportunity cost", "With limited capital, the committee preferred Alphabet's faster growth, which was pitched at the same meeting."],
      ["How we track it", "The fund records the return of every declined pitch against the S&P 500 from the pitch date, so the committee's judgment can be measured over time."],
    ],
    icRationale: "Not approved. The committee preferred Alphabet for the available capital and was not convinced that data center growth would outrun the PC decline.",
    vote: "Not approved 2–5",
    file: "2016-01-06-intc-pitch.md",
  },
  {
    slug: "amzn-2018-initiation",
    ticker: "AMZN", exchange: "NASDAQ", company: "Amazon.com, Inc.",
    sector: "Consumer Discretionary", industry: "Broadline Retail",
    type: "Initiation", date: "2018-02-16", rating: "BUY",
    team: "Consumer Discretionary team",
    decision: "Approved", decisionDate: "2018-02-22",
    executed: { date: "2018-02-26", price: 1521.95 },
    price: 1448.69, target: 1850,
    kpis: [["AWS revenue growth", "43%", "2017, to $17.5B"], ["Free cash flow", "$8.4B", "Trailing 12 months"]],
    headline: "AWS, advertising and the Prime flywheel",
    thesis: [
      "We recommend initiating a position in Amazon. Investors still judge Amazon on thin reported earnings. We think it is really two leading businesses, a global retail platform and the largest cloud provider, with a third, advertising, now growing quickly.",
      "In 2017, Amazon Web Services grew 43% to $17.5 billion of revenue and earned $4.3 billion of operating income, more than the whole company earned. Advertising and other revenue grew about 58% to $4.7 billion.",
      "Amazon reinvests most of its cash flow in fulfillment, video and new markets, so earnings understate its earning power. Valued on segment profits and free cash flow, the stock is easier to justify than its P/E suggests.",
    ],
    catalysts: [
      ["AWS margin disclosure", "Each quarter AWS shows operating leverage as revenue scales faster than costs."],
      ["Advertising growth", "Sponsored product ads monetize high-intent shopping traffic with very little added cost."],
      ["Whole Foods integration", "Prime benefits in Whole Foods stores and grocery delivery extend Amazon into a large new category."],
      ["International progress", "Losses in India and other markets should narrow as those businesses scale."],
    ],
    risks: [
      ["Valuation", "About 100x trailing earnings leaves little room for disappointment."],
      ["Spending", "Heavy investment could keep margins low longer than expected."],
      ["Regulation and politics", "Amazon's size in retail draws growing political scrutiny."],
      ["Cloud competition", "Microsoft Azure and Google Cloud are investing heavily to catch up with AWS."],
    ],
    financials: {
      note: "$ billions.",
      cols: ["2015", "2016", "2017"],
      rows: [
        ["Net sales", "107.0", "136.0", "177.9"],
        ["Sales growth", "20%", "27%", "31%"],
        ["AWS revenue", "7.9", "12.2", "17.5"],
        ["AWS operating income", "1.5", "3.1", "4.3"],
        ["Net income", "0.6", "2.4", "3.0"],
        ["Free cash flow", "7.3", "10.5", "8.4"],
      ],
    },
    valuation: {
      method: "Sum of the parts (2019 estimates)",
      rows: [["AWS at 20x operating income", "~$470B"], ["Retail and advertising at 1.5x sales", "~$420B"], ["Net cash", "~$10B"], ["Equity value per share", "~$1,850"], ["12-month target", "$1,850"]],
      text: "We value the businesses separately because they have very different economics. AWS is valued like a fast-growing software company, retail on sales because its profits are reinvested, and we add net cash.",
    },
    caseTitle: "Why we are buying Amazon",
    caseSections: [
      ["Two category leaders in one stock", "Amazon is the largest online retailer in the US and the largest cloud infrastructure provider in the world. Either business alone would be a reasonable investment. Together, they share technology, data and customers."],
      ["AWS is early", "Most enterprise computing still runs in companies' own data centers. As those workloads move to the cloud over the next decade, AWS's lead in breadth of services and scale should let it capture the largest share and grow margins as it does."],
      ["Advertising changes the margin story", "Shoppers search Amazon with the intent to buy, which makes its ads valuable. Advertising carries far higher margins than retail, so its growth lifts the profitability of the whole company."],
      ["The Prime flywheel", "Prime members buy more, more often. Each new benefit, from video to faster shipping to Whole Foods discounts, improves retention and gives Amazon more data to improve the service."],
      ["What would make us wrong", "AWS growth falling below 25% with no margin expansion, or spending that keeps free cash flow flat for several years. Either would suggest the reinvestment is earning poor returns."],
    ],
    icRationale: "The committee approved Amazon over the GE turnaround pitch at the same meeting. It preferred durable growth at a high multiple to an uncertain turnaround at a low one.",
    vote: "Approved 6–1",
    file: "2018-02-16-amzn-initiation.md",
  },
  {
    slug: "ge-2018-pitch",
    ticker: "GE", exchange: "NYSE", company: "General Electric Company",
    sector: "Industrials", industry: "Industrial Conglomerates",
    type: "Initiation", date: "2018-02-16", rating: "BUY",
    team: "Industrials team",
    decision: "Not approved", decisionDate: "2018-02-22",
    price: 15.05, target: 19,
    kpis: [["2018 EPS guidance", "$1.00–1.07", "Adjusted"], ["Dividend", "$0.12", "Quarterly, cut in half"]],
    headline: "A contrarian bet on a turnaround",
    thesis: [
      "The team recommended General Electric after a roughly 50% decline in a year. A new CEO, a reset dividend and a plan to focus on Aviation, Power and Healthcare could make it a contrarian buy.",
      "John Flannery became CEO in August 2017. He cut the dividend in half, announced about $20 billion of divestitures and opened a review of the company's structure. GE Aviation, with a large installed base of jet engines, remained a high-quality franchise.",
      "The team argued that sentiment was so negative that any stabilization in Power or clarity on insurance liabilities could lift the shares.",
    ],
    catalysts: [
      ["Portfolio review", "A decision on separating businesses, such as listing Healthcare, could unlock value."],
      ["Aviation strength", "Commercial aircraft engine demand and service revenue continue to grow."],
      ["Power stabilization", "Cost cuts in the gas turbine business could stop the earnings decline."],
      ["Divestitures", "Asset sales would reduce debt and simplify the company."],
    ],
    risks: [
      ["Insurance reserves", "GE took a $6.2 billion after-tax charge in January 2018 for its long-term-care insurance book and expects to put about $15 billion into reserves over seven years."],
      ["Power downturn", "Demand for gas turbines is in a deep slump, with no clear bottom."],
      ["SEC investigation", "The SEC is investigating GE's accounting for insurance reserves and long-term service contracts."],
      ["Balance sheet", "Pension deficits and GE Capital's debt make the downside hard to size."],
    ],
    financials: {
      note: "$ billions except per share.",
      cols: ["2016", "2017"],
      rows: [
        ["Revenue", "123.7", "122.1"],
        ["Adjusted EPS ($)", "1.49", "1.05"],
        ["Annual dividend per share ($)", "0.93", "0.84"],
        ["2018 adjusted EPS guidance ($)", "—", "1.00–1.07"],
      ],
    },
    valuation: {
      method: "Earnings multiple",
      rows: [["2018E adjusted EPS", "~$1.03"], ["Target multiple", "18x"], ["12-month target", "$19"]],
      text: "The team applied a market-level multiple, arguing that GE's industrial franchises deserved at least that once balance sheet uncertainty cleared.",
    },
    caseTitle: "Why the committee passed on GE",
    caseSections: [
      ["The bull case presented", "Aviation's installed base produces decades of high-margin service revenue, and Healthcare could be worth more on its own. Sentiment was at a historic low."],
      ["Downside too hard to size", "Insurance reserves, pension deficits and GE Capital's debt meant members could not estimate how bad the worst case might be."],
      ["No floor in Power", "The gas turbine market was still deteriorating, and Power was a large share of industrial profits."],
      ["Accounting questions", "An open SEC investigation added a risk the team could not evaluate."],
      ["How we track it", "The fund records the return of every declined pitch against the S&P 500 from the pitch date, so the committee's judgment can be measured over time."],
    ],
    icRationale: "Not approved. The committee preferred Amazon's growth profile for the available capital and judged GE's balance sheet risk too uncertain to underwrite.",
    vote: "Not approved 1–6",
    file: "2018-02-16-ge-pitch.md",
  },
  {
    slug: "amd-2024-initiation",
    ticker: "AMD", exchange: "NASDAQ", company: "Advanced Micro Devices, Inc.",
    sector: "Information Technology", industry: "Semiconductors",
    type: "Initiation", date: "2024-08-02", rating: "BUY",
    team: "Information Technology team",
    decision: "Approved", decisionDate: "2024-08-05",
    executed: { date: "2024-08-06", price: 130.18 },
    price: 132.5, target: 185,
    kpis: [["Data center growth", "115%", "Q2 2024, to $2.8B"], ["2024 AI GPU outlook", ">$4.5B", "Raised July 30"]],
    headline: "The second source for AI accelerators",
    thesis: [
      "We recommend initiating a position in AMD after a roughly 40% pullback from its March 2024 high. Data center revenue more than doubled year over year in Q2, and MI300 accelerator sales passed $1 billion in a single quarter for the first time.",
      "AI buyers want an alternative to Nvidia for supply, pricing and negotiating leverage. MI300X is the first product to offer one at scale, and AMD has committed to a new accelerator every year.",
      "The early-August market selloff took AMD to about $130. That gives us a better margin of safety on a business whose data center segment is now its largest.",
    ],
    catalysts: [
      ["MI325X and an annual cadence", "New accelerators launching in late 2024 and 2025 keep AMD competitive on memory capacity and performance."],
      ["Hyperscaler deployments", "Large cloud customers are expanding MI300X deployments for AI inference."],
      ["EPYC share gains", "Server CPU share gains continue on performance per watt."],
      ["PC recovery", "AI-capable Ryzen PCs and an aging installed base support a client recovery."],
    ],
    risks: [
      ["Nvidia's software lead", "CUDA is deeply entrenched. AMD's ROCm software must keep improving for customers to switch."],
      ["Supply constraints", "Advanced packaging and high-bandwidth memory capacity could limit shipments."],
      ["Export controls", "Restrictions on AI chip sales to China limit the market."],
      ["Volatility", "The stock trades at a premium multiple and swings with AI sentiment."],
    ],
    financials: {
      note: "$ billions. Q2 2024 reported July 30, 2024.",
      cols: ["2022", "2023", "Q2 2024"],
      rows: [
        ["Revenue", "23.6", "22.7", "5.8"],
        ["Revenue growth", "44%", "−4%", "9%"],
        ["Data Center revenue", "6.0", "6.5", "2.8"],
        ["Data Center growth", "64%", "7%", "115%"],
        ["Non-GAAP gross margin", "51%", "50%", "53%"],
      ],
    },
    valuation: {
      method: "Forward earnings multiple",
      rows: [["2025E EPS (non-GAAP)", "~$5.30"], ["Target multiple", "35x"], ["12-month target", "$185"]],
      text: "A 35x multiple reflects data center growth well above the semiconductor industry's. If AI GPU revenue keeps beating guidance, earnings estimates and the target would rise.",
    },
    caseTitle: "Why we are buying AMD",
    caseSections: [
      ["Customers want a second source", "AI accelerators are the most supply-constrained part of the data center. Buyers who depend on one supplier pay higher prices and wait longer. AMD's MI300X gives them an alternative, and large customers have publicly committed to deploying it."],
      ["A proven execution record", "Under Lisa Su, AMD went from near bankruptcy to taking significant server CPU share from Intel. That record of delivering roadmaps on time gives us confidence in its annual accelerator cadence."],
      ["Data center is now the largest segment", "At $2.8 billion a quarter and growing over 100%, data center is changing AMD's mix toward higher margins and more durable demand."],
      ["A better entry price", "The pullback from March and the early-August selloff mean we are buying about 40% below the recent high, without any break in the fundamental story."],
      ["What would make us wrong", "Customers pausing MI300 orders, AMD missing its annual product cadence, or gross margins falling as it discounts to win share."],
    ],
    icRationale: "The committee approved a full position during the market selloff. It judged that the price decline reflected market fear rather than any change in AMD's data center trajectory.",
    vote: "Approved 6–1",
    file: "2024-08-02-amd-initiation.md",
  },
  {
    slug: "aapl-2026-review",
    ticker: "AAPL", exchange: "NASDAQ", company: "Apple Inc.",
    sector: "Information Technology", industry: "Technology Hardware",
    type: "Update", date: "2026-10-02", rating: "HOLD",
    team: "Information Technology team",
    heldSince: "2016-01-04", costPrice: 105.35,
    price: 333.69, target: 350,
    kpis: [["Weight in fund", "~41%", "Largest position"], ["Total return held", "+1,309%", "S&P 500 TR +356%"]],
    headline: "The thesis worked; now the question is position size",
    thesis: [
      "Apple has returned about 1,309% since we bought it, against 356% for the S&P 500 Total Return. The 2015 thesis was that a loyal installed base and fast-growing Services were being valued as a declining hardware business. That has largely played out.",
      "Services became a business of more than $100 billion a year with gross margins far above hardware. Heavy buybacks substantially cut the share count, so earnings per share grew faster than revenue.",
      "We keep Apple at Hold. The ecosystem and cash generation are intact, but the valuation is far above the 11.6x earnings we paid. Growth now depends more on Services and on whether Apple delivers competitive AI features.",
    ],
    catalysts: [
      ["AI features", "Delivering useful on-device and cloud AI features could restart device upgrade demand."],
      ["Services growth", "Subscriptions, payments and advertising continue to grow faster than hardware."],
      ["Capital return", "Continued buybacks support earnings per share."],
      ["New categories", "Wearables and new device types add to the installed base."],
    ],
    risks: [
      ["App Store regulation", "US court rulings and EU rules threaten App Store fees, a key source of Services profit."],
      ["AI competition", "Rivals may move faster on AI assistants and features."],
      ["Valuation", "A premium multiple leaves less room for disappointment."],
      ["Concentration", "At about 41% of the fund, Apple dominates the portfolio's risk."],
    ],
    returns: true,
    valuation: {
      method: "Review target",
      rows: [["Price at review (Oct 2, 2026)", "$333.69"], ["12-month target", "$350"], ["Implied return", "~5%"]],
      text: "Our target assumes earnings grow in line with Services and buybacks, with no expansion in the multiple. A modest expected return supports holding rather than adding.",
    },
    caseTitle: "Why we continue to hold Apple",
    caseSections: [
      ["What went right", "Our 2015 pitch said the market was valuing Apple's ecosystem like a declining hardware maker. Since then, the installed base grew, Services became a large high-margin business, and buybacks shrank the share count. The multiple investors pay rose from about 11x to a premium to the market."],
      ["Why not sell", "None of our exit conditions has been met. The installed base has not shrunk, the capital return program continues, and Services is still growing. In a real account, selling would also realize a very large taxable gain."],
      ["Why not add", "At today's price, we no longer have the margin of safety we bought with. Most of the upside from re-rating has already happened, and future returns depend mostly on earnings growth."],
      ["Position size", "Apple has grown to about 41% of the fund through appreciation, above the fund's 10% single-position guideline. The committee will consider trimming to reduce concentration risk, with proceeds kept in cash or used for new pitches."],
      ["What would change our view", "A sustained slowdown in Services, a forced change to App Store economics, or evidence that AI features are moving upgrade demand to rival platforms."],
    ],
    icRationale: "The committee reaffirmed the position at Hold and asked the Information Technology team to present a trimming proposal at the next meeting.",
    vote: "Hold reaffirmed",
    file: "2026-09-28-aapl-update.md",
  },
  {
    slug: "googl-2026-review",
    ticker: "GOOGL", exchange: "NASDAQ", company: "Alphabet Inc.",
    sector: "Communication Services", industry: "Interactive Media & Services",
    type: "Update", date: "2026-10-02", rating: "HOLD",
    team: "Communication Services team",
    heldSince: "2016-01-11", costPrice: 733.07,
    price: 343.5, target: 365,
    kpis: [["Weight in fund", "~31%", "Second-largest"], ["Total return held", "+846%", "S&P 500 TR +377%"]],
    headline: "AI is the central debate; we hold",
    thesis: [
      "Alphabet has returned about 846% since we bought it, against 377% for the S&P 500 Total Return. The 2016 thesis, mobile search, YouTube and cost discipline, played out, and Google Cloud grew from an afterthought into a large, profitable segment.",
      "Capital returns arrived as we hoped. Alphabet now pays a regular dividend, introduced in 2024, alongside large buybacks.",
      "The central question now is generative AI. Chat assistants challenge the idea that Search is untouchable. Alphabet has responded with its Gemini models and AI features in Search, and its own TPU chips give it a cost advantage in running AI.",
    ],
    catalysts: [
      ["Gemini adoption", "Wider use of Gemini in Search, Workspace and Android could defend and grow engagement."],
      ["Google Cloud", "AI demand is driving cloud growth and margin expansion."],
      ["TPU advantage", "In-house AI chips lower the cost of serving AI queries."],
      ["Waymo", "Commercial robotaxi expansion could give Other Bets real value."],
    ],
    risks: [
      ["Search disruption", "AI assistants could take share of information queries."],
      ["Antitrust remedies", "US courts found Google held an illegal search monopoly. Remedies stopped short of a breakup, but appeals and further limits remain possible."],
      ["AI capital spending", "Data center investment is rising sharply and must earn adequate returns."],
      ["Ad market cyclicality", "Advertising is sensitive to the economy."],
    ],
    returns: true,
    valuation: {
      method: "Review target",
      rows: [["Price at review (Oct 2, 2026)", "$343.50"], ["12-month target", "$365"], ["Implied return", "~6%"]],
      text: "Our target assumes steady growth in Search and faster growth in Cloud, at a multiple similar to today's. Upside from AI leadership is balanced against disruption risk.",
    },
    caseTitle: "Why we continue to hold Alphabet",
    caseSections: [
      ["What went right", "Every part of the 2016 thesis worked: mobile search monetized well, YouTube became a major advertising business, and the Alphabet structure brought cost discipline and capital returns. Cloud was a bonus we did not model."],
      ["The AI question", "The biggest risk to Search in two decades has arrived. So far, Search revenue has kept growing as Google added AI answers. Alphabet has one of the strongest AI research teams and its own chips, so it is a likely winner of the shift, not only a target of it."],
      ["Why not add", "The stock has re-rated as investors gained confidence in Alphabet's AI position. At today's price, the balance between AI upside and Search disruption risk looks fair."],
      ["Position size", "At about 31% of the fund, Alphabet is a large position. Together with Apple, the fund is heavily concentrated in two technology platforms. The committee will review this alongside the Apple trim."],
      ["What would change our view", "Clear evidence that AI assistants are taking Search share, or remedies that end Google's default-search agreements in a way that reduces traffic."],
    ],
    icRationale: "The committee reaffirmed the position at Hold and will review fund-level concentration in technology platforms.",
    vote: "Hold reaffirmed",
    file: "2026-09-28-googl-update.md",
  },
  {
    slug: "amzn-2026-review",
    ticker: "AMZN", exchange: "NASDAQ", company: "Amazon.com, Inc.",
    sector: "Consumer Discretionary", industry: "Broadline Retail",
    type: "Update", date: "2026-10-02", rating: "HOLD",
    team: "Consumer Discretionary team",
    heldSince: "2018-02-26", costPrice: 1521.95,
    price: 251.52, target: 275,
    kpis: [["Weight in fund", "~11%", "Smallest position"], ["Total return held", "+231%", "S&P 500 TR +217%"]],
    headline: "Three engines bigger than ever; AI spending is the debate",
    thesis: [
      "Amazon has returned about 231% since we bought it, slightly ahead of the 217% S&P 500 Total Return. It is the fund's weakest relative performer, mainly because of the 2021–2022 overbuild in fulfillment capacity and slower cloud growth in 2023.",
      "The three engines from our 2018 thesis are all larger and more profitable: AWS is a business of more than $100 billion a year, advertising is one of Amazon's most profitable lines, and retail margins have recovered after a cost reset and a regionalized delivery network.",
      "The current debate is AI capital spending. Amazon is investing heavily in data centers and its own Trainium chips, and has a large investment in Anthropic. That lowers free cash flow today but positions AWS for AI workloads.",
    ],
    catalysts: [
      ["AWS AI demand", "AI training and inference workloads are reaccelerating AWS growth."],
      ["Advertising", "Prime Video ads and sponsored products keep growing high-margin revenue."],
      ["Retail efficiency", "Regional fulfillment and automation lower the cost to serve each order."],
      ["Free cash flow recovery", "Cash flow should rise as AI capacity begins to earn revenue."],
    ],
    risks: [
      ["AI returns", "Data center spending may not earn adequate returns if AI demand slows."],
      ["Cloud competition", "Microsoft and Google compete hard for AI workloads."],
      ["Regulation", "The FTC antitrust case against Amazon's marketplace practices is ongoing."],
      ["Consumer slowdown", "Retail is sensitive to the economy."],
    ],
    returns: true,
    valuation: {
      method: "Review target",
      rows: [["Price at review (Oct 2, 2026)", "$251.52"], ["12-month target", "$275"], ["Implied return", "~9%"]],
      text: "Amazon has the most upside of our holdings at its current valuation. Long stretches of flat performance since 2020 have left its multiple more reasonable than when we bought.",
    },
    caseTitle: "Why we continue to hold Amazon",
    caseSections: [
      ["What went right", "AWS and advertising grew as our 2018 pitch expected, and both now produce most of Amazon's profit. The Prime flywheel kept customers loyal through the pandemic and after."],
      ["What went wrong", "Amazon nearly doubled its fulfillment network during the pandemic and then had too much capacity as demand normalized. Cloud customers also cut costs in 2023. Both weighed on the stock for several years."],
      ["Why we hold", "Those problems have been addressed: retail margins recovered, and AWS growth is picking up with AI demand. The stock's relative underperformance has made its valuation more attractive."],
      ["The AI bet", "Amazon's heavy AI spending is the key risk and the key opportunity. If AWS captures a large share of AI workloads, today's spending will look cheap. We are watching AWS growth and free cash flow closely."],
      ["What would change our view", "AWS losing share in AI workloads, or several years of capital spending without a recovery in free cash flow."],
    ],
    icRationale: "The committee reaffirmed the position at Hold and noted Amazon as the first candidate to add to if proceeds from an Apple trim become available.",
    vote: "Hold reaffirmed",
    file: "2026-09-28-amzn-update.md",
  },
  {
    slug: "amd-2026-review",
    ticker: "AMD", exchange: "NASDAQ", company: "Advanced Micro Devices, Inc.",
    sector: "Information Technology", industry: "Semiconductors",
    type: "Update", date: "2026-10-02", rating: "HOLD",
    team: "Information Technology team",
    heldSince: "2024-08-06", costPrice: 130.18,
    price: 633.91, target: 650,
    kpis: [["Weight in fund", "~16%", "Up from 3% of capital"], ["Total return held", "+387%", "S&P 500 TR +51%"]],
    headline: "The second-source thesis played out",
    thesis: [
      "AMD has returned about 387% in just over two years, against 51% for the S&P 500 Total Return. It is the fund's best performer relative to the market.",
      "Our 2024 thesis was that AI buyers wanted a credible alternative to Nvidia. That happened: large customers signed multi-year accelerator agreements, including OpenAI's October 2025 commitment to deploy AMD Instinct GPUs at multi-gigawatt scale.",
      "AMD kept its annual accelerator cadence with the MI325, MI350 and MI400 series, and bought ZT Systems to design complete AI server racks. EPYC server CPUs kept gaining share.",
    ],
    catalysts: [
      ["MI400 rack-scale systems", "Full AI racks compete directly with Nvidia's integrated systems."],
      ["Customer deployments", "Multi-year agreements begin shipping in volume."],
      ["EPYC", "Server CPU share gains continue as AI data centers also need general-purpose compute."],
      ["Software", "ROCm improvements lower the cost for customers to switch."],
    ],
    risks: [
      ["AI spending cycle", "A pause in hyperscaler spending would hit AMD harder than our other holdings."],
      ["Nvidia", "Nvidia remains the leader, with a faster product cadence and deeper software ecosystem."],
      ["Execution", "Rack-scale systems are more complex to deliver than chips."],
      ["Valuation", "At nearly five times our cost, much of the success is priced in."],
    ],
    returns: true,
    valuation: {
      method: "Review target",
      rows: [["Price at review (Oct 2, 2026)", "$633.91"], ["12-month target", "$650"], ["Implied return", "~3%"]],
      text: "After a nearly fivefold gain, our target implies limited near-term upside. We hold for the long-term data center opportunity but would not add at this price.",
    },
    caseTitle: "Why we continue to hold AMD",
    caseSections: [
      ["What went right", "Our 2024 pitch argued that customers wanted a second source of AI accelerators and that a 40% pullback offered a good entry. Both proved correct: AMD won large multi-year commitments, and the stock nearly quintupled."],
      ["Why not sell", "The long-term opportunity in AI data centers remains large, and AMD is now an established supplier rather than a hopeful one. None of our exit conditions has been met."],
      ["Why not add", "The price now reflects much of the success. At nearly five times our cost, new money would buy much less margin of safety, and AMD is the holding most sensitive to a slowdown in AI spending."],
      ["Position size", "AMD has grown from about 3% of the fund's capital at purchase to about 16% of the fund. That is above the 10% guideline, and the committee will review it alongside the Apple trim."],
      ["What would change our view", "Customers delaying accelerator deployments, AMD falling behind Nvidia's product cadence, or gross margins falling as competition intensifies."],
    ],
    icRationale: "The committee reaffirmed the position at Hold and asked the team to monitor customer deployment milestones each quarter.",
    vote: "Hold reaffirmed",
    file: "2026-09-28-amd-update.md",
  },
];
